site_name: SmartPouch_v2 Data Experiment Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Overview: Overview.md
  - Data: Data.md
  - Mermaid:
    - Mermaid example: example\mermaid_demo.md



markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format