site_name: SmartPouch_v2 Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - toc.integrate

nav:
  - Home: index.md
  - Data Specification:
    - Overview: data_specification.md
    - Feature Engineering: feature_engineering.md
    - Model Training: 
      - Model Evaluation: model_evaluation.md
      - Deployment: deployment.md
    - One Record: one_record_implementation.md
  #- Worklog:
  #  - Overview: worklog/index.md
  #  - Usage Guide: worklog/usage_guide.md
  #  - 2024:
  #    - March: worklog/2024/03.md
  #    - February: worklog/2024/02.md
  #    - January: worklog/2024/01.md
  #- About Us: about.md

plugins:
  - search
  - git-revision-date-localized


extra:
  revision:
    date_format: '%Y-%m-%d'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/movement-recognition
      name: GitHub
  generator: false


markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js